name: build

on:
  push:
    branches: [ master ]
    paths-ignore: 
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_proj_version.outputs.PKG_VERSION }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.204
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Package
      run: dotnet pack --no-restore -o packaging --configuration Release
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: nupkg
        path: packaging
    - name: Get version
      id: set_proj_version
      shell: pwsh
      run: |
        [xml]$nuspec = Get-Content Socrata\Socrata.csproj
        $version=$nuspec.project.propertygroup.version
        echo "PKG_VERSION=$version" >> $GITHUB_OUTPUT
    env:
      SODA_USERNAME: "${{ secrets.SODA_USERNAME }}"
      SODA_PASSWORD: "${{ secrets.SODA_PASSWORD }}"

  deploy:
    needs: build
    environment:
      name: production
      url: https://www.nuget.org/packages/socrata.dotnet/
    name: Sign and publish
    runs-on: windows-latest
    steps:
      - name: Download Package artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkg
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: latest
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.200

      - name: Push to NuGet
        run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
