name: pullrequest

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.0
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Package
      run: dotnet pack --no-restore --output ./packaging

    env:
      SODA_USERNAME: "${{ secrets.SODA_USERNAME }}"
      SODA_PASSWORD: "${{ secrets.SODA_PASSWORD }}"
